-- MySQL Script generated by MySQL Workbench
-- Sat Jul 10 01:06:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cruding
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cruding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cruding` DEFAULT CHARACTER SET utf8 ;
USE `db_cruding` ;

-- -----------------------------------------------------
-- Table `db_cruding`.`typeUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cruding`.`typeUsers` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cruding`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cruding`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `token` VARCHAR(45) NULL,
  `typeUsers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_typeUsers_idx` (`typeUsers_id` ASC),
  CONSTRAINT `fk_users_typeUsers`
    FOREIGN KEY (`typeUsers_id`)
    REFERENCES `db_cruding`.`typeUsers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cruding`.`typeImovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cruding`.`typeImovel` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cruding`.`imoveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cruding`.`imoveis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `typeImovel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imoveis_typeImovel1_idx` (`typeImovel_id` ASC),
  CONSTRAINT `fk_imoveis_typeImovel1`
    FOREIGN KEY (`typeImovel_id`)
    REFERENCES `db_cruding`.`typeImovel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cruding`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cruding`.`venda` (
  `id` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  `imoveis_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_users1_idx` (`users_id` ASC),
  INDEX `fk_venda_imoveis1_idx` (`imoveis_id` ASC),
  CONSTRAINT `fk_venda_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_cruding`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_imoveis1`
    FOREIGN KEY (`imoveis_id`)
    REFERENCES `db_cruding`.`imoveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
